---
- name: Ensure MariaDB repo-key is present
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: F1656F24C74CD1D8

- name: Ensure OpenXChange repo-key is present
  apt_key:
    url: http://software.open-xchange.com/oxbuildkey.pub
    state: present

- name: Ensure repositories are included
  copy:
    src: files/packages/
    dest: /etc/apt/sources.list.d/
    owner: root
    group: root
    mode: 0755

- name: Ensure packages are installed
  apt:
    name:
      - mariadb-server
      - mariadb-client
      - python3-pymysql
      - open-xchange
      - open-xchange-authentication-database
      - open-xchange-grizzly
      - open-xchange-admin
      - open-xchange-appsuite
      - open-xchange-appsuite-backend
      - open-xchange-appsuite-manifest
    update_cache: yes